spring:
  datasource:
#    url: jdbc:mysql://database-yangyu.cru4mkouy1rr.ap-northeast-2.rds.amazonaws.com:3306/programmers?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/programmers?createDatabaseIfNotExist=true
#    username: ${rds.username}
#    password: ${rds.password}
